server:
  logLevel: info
  options:
    trustProxy: true

template:
  title: Linked Open Data (by Code for Germany)
  disableHeader: false
  disableFooter: false
  files:
    header: file:header.hbs
    footer: file:footer.hbs
  styles:
    - /static-assets/style.css

globals:
  datasetBaseUrl: env:DATASET_BASE_URL
  endpoints:
    default:
      url: /query

plugins:
  welcome:
    module: trifid-core/plugins/view.js
    paths: /
    methods: GET
    config:
      path: file:welcome.hbs

  static-assets:
    module: trifid-core/plugins/static.js
    paths: /static-assets
    config:
      directory: file:static

  entity-renderer:
    module: "@zazuko/trifid-entity-renderer"
    config:
      followRedirects: false
      showNamedGraphs: false
      labelLoader:
        chunkSize: 50
        concurrency: 2
        timeout: 4000

  yasgui:
    module: trifid-plugin-yasgui
    paths:
      - /sparql
      - /sparql/
    config:
      defaultQuery: |
        PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
        PREFIX codeforde: <https://lod.codefor.de/vocabulary/codeforde/>
        PREFIX dbo: <https://dbpedia.org/ontology/>
        PREFIX dct: <http://purl.org/dc/terms/>
        PREFIX foaf: <http://xmlns.com/foaf/0.1/>
        PREFIX geo: <http://www.opengis.net/ont/geosparql#>
        PREFIX gn: <http://www.geonames.org/ontology#>
        PREFIX juso: <http://rdfs.co/juso/>
        PREFIX owl: <http://www.w3.org/2002/07/owl#>
        PREFIX ql: <http://semweb.mmlab.be/ns/ql#>
        PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
        PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
        PREFIX rml: <http://semweb.mmlab.be/ns/rml#>
        PREFIX rr: <http://www.w3.org/ns/r2rml#>
        PREFIX schema: <http://schema.org/>
        PREFIX status: <http://www.w3.org/2003/06/sw-vocab-status/ns#>
        PREFIX wdt: <http://www.wikidata.org/prop/direct/>
        PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

        # example query: municipalities with the highest population density
        SELECT ?municipality ?name ?population ?area (?population/(?area/1000000) as ?pplPerKm2) {
          ?municipality rdf:type codeforde:Gemeinde;
            juso:name ?name;
            geo:hasGeometry/geo:hasMetricArea ?area;
            gn:population ?population.
        }
        ORDER BY DESC(?pplPerKm2)
        LIMIT 10

  sparql-proxy:
    module: "@zazuko/trifid-plugin-sparql-proxy"
    paths: /query
    config:
      allowRewriteToggle: false
      rewrite: false
      rewriteQuery: false
      rewriteResults: false
      endpointUrl: env:SPARQL_ENDPOINT_URL
      formats:
        ttl: "text/turtle"
        jsonld: "application/ld+json"
        xml: "application/rdf+xml"
        nt: "application/n-triples"
        trig: "application/trig"
        csv: "text/csv"
