name: CI
on:
  [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Test (build api)
      uses: docker/build-push-action@v6
      with:
        context: api
        platforms: linux/amd64,linux/arm64
        push: false
        cache-from: type=gha
        cache-to: type=gha,mode=max
    - name: Test (build frontend)
      uses: docker/build-push-action@v6
      with:
        context: frontend
        platforms: linux/amd64,linux/arm64
        push: false
        cache-from: type=gha
        cache-to: type=gha,mode=max

  build-and-push:
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/main'
    permissions:
      packages: write
      contents: read
      attestations: write
      id-token: write
    steps:
    - uses: actions/checkout@v4
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Fetch commit hash
      id: hash
      run: echo "::set-output name=hash::$(echo $GITHUB_SHA | head -c7)"
    - name: Fetch current date and time
      id: datetime
      run: echo "::set-output name=datetime::$(date -u +'%Y-%m-%dT%H.%M.%SZ')"
    - name: Build and push api container
      uses: docker/build-push-action@v6
      with:
        context: api
        platforms: linux/amd64,linux/arm64
        push: true
        tags: ghcr.io/${{github.repository}}-api:v1_${{steps.hash.outputs.hash}}_${{steps.datetime.outputs.datetime}}
        cache-from: type=gha
        cache-to: type=gha,mode=max
    - name: Build and push frontend container
      uses: docker/build-push-action@v6
      with:
        context: frontend
        platforms: linux/amd64,linux/arm64
        push: true
        tags: ghcr.io/${{github.repository}}-frontend:v1_${{steps.hash.outputs.hash}}_${{steps.datetime.outputs.datetime}}
        cache-from: type=gha
        cache-to: type=gha,mode=max
